services:
  dash-knowledge-viewer:
    build: .
    container_name: dash-knowledge-viewer
    restart: always

    environment:
      KNOWLEDGE_DB_PATH: /app

    volumes:
      - /opt/knowledge-db/data:/app/data:ro
      - /opt/knowledge-db/markdown:/app/markdown:ro
      - /opt/knowledge-db/index.json:/app/index.json:ro

    ports:
      - "9001:8050"
